### ISSUE TITLE
E/FrameEvents( 3079): updateAcquireFence: Did not find frame.

### ISSUE THREAD

**Issue by function2000** [MarlonJD/babylonjs_viewer#10]
I run and get below issue, please guide:
E/FrameEvents( 3079): updateAcquireFence: Did not find frame.

**Comment by hellhorse123** [comment]
I will describe the problem in more detail: on android, during the display of 3d scenes, errors "updateAcquireFence: Did not find frame" are poured into the console, because of this, the 3d scene slows down. Is there a fix for this bug?
<img width="840" alt="image" src="https://github.com/MarlonJD/babylonjs_viewer/assets/48678379/ce958d2e-b52f-4a34-836e-af215e9fa20b">

**Comment by MarlonJD** [comment]
Can you give me the example code for debugging?
